name: compability-workflow
run-name: Build for multiple Swift versions
on: [push]
jobs:
  swift-6_0-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker run --rm -v "$PWD:/code" -w /code swift:6.0 swift build
  swift-5_10-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker run --rm -v "$PWD:/code" -w /code swift:5.10 swift build
  swift-5_9-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker run --rm -v "$PWD:/code" -w /code swift:5.9 swift build