name: Test Linux Platform
on: [push]

jobs:
  Test-Linux-Swift-60:
    runs-on: ubuntu-latest
    container:
      image: swift:6.0
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: swift test --scratch-path /tmp/swifter-build-6.0 --no-parallel
  Test-Linux-Swift-61:
    runs-on: ubuntu-latest
    container:
      image: swift:6.1
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: swift test --scratch-path /tmp/swifter-build-6.1 --no-parallel
  Test-Linux-Swift-62:
    runs-on: ubuntu-latest
    container:
      image: swift:6.2
      options: --cap-add=SYS_PTRACE --security-opt seccomp=unconfined --security-opt apparmor=unconfined
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: swift test --scratch-path /tmp/swifter-build-6.2 --no-parallel
